### ISSUE TITLE
Add read-only states for components

### ISSUE THREAD

**Issue by bendansby** [NoRedInk/noredink-ui#1099]
This state supports a tooltip and is focusable by users, but is otherwise unresponsive to input. Read more here: https://paper.dropbox.com/doc/UI-Style-Guide-and-Caveats--Bp4fqW9iugIrl0HvFqdDzOlbAg-PvOLxeX3oyujYEzdJx5pu#:uid=089559839007265064583003&h2=:under-construction:-Read-Only

The following components need read-only states
- [ ] Button
- [ ] Select
- [ ] Text input
 -- note that this component already has a "read-only" state—it should be preserved but renamed "selectable"
- [ ] Toggle
- [ ] Checkbox
- [ ] Radio button
- [ ] Text area

**Comment by tesk9** [comment]
Can this be closed in favor of the "helpfully disabled" work in Linear?

**Comment by bendansby** [comment]
Yup!
