### ISSUE TITLE
ClickableSvg: Rename tertiary style and add new tertiary style matching the tertiary style of Button

### ISSUE THREAD

**Issue by bendansby** [NoRedInk/noredink-ui#1185]

**Comment by tesk9** [comment]
How does `quaternary` sound? 😅

**Comment by bendansby** [comment]
Plus one!

**Comment by tesk9** [comment]
Cool! I think probably a two-phase change is good idea here:

- dupe the current tertiary styles and call them quaternary
- release, upgrade, find-and-replace all tertiary uses to quarternary
- and then edit the tertiary styles to match the existing tertiary styles

I can get started on it, if you want...? LMK
