### ISSUE TITLE
Menu: make text label optionally hidden (tooltip appears in lieu of text label)

### ISSUE THREAD

**Issue by bendansby** [NoRedInk/noredink-ui#1190]

**Comment by tesk9** [comment]
I think once ClickableSvg supports rightIcon and Menu can conveniently use it, then this will be kind of implicitly done? It will be ClickableSvg + Menu + Tooltip. (This is for the gear icon on manage classes, right?)

**Comment by bendansby** [comment]
Right, I think that should work 👍
