### ISSUE TITLE
Add `openInNewTab` affordance automatically when `linkExternal` is used

### ISSUE THREAD

**Issue by tesk9** [NoRedInk/noredink-ui#1214]
This [slack conversation](https://noredink.slack.com/archives/C02NVG4M45U/p1669918324279939) has some discussion on what we'd like. I think ultimately, we should be adding the icon in the same spot/using the same pattern every time.

My inclination is use `rightIcon`, rather than `icon`, so that the accessible name includes the imp. extra info ("opens in a new tab") at the end rather than at the beginning.

I don't think we'll be able to add tooltips really conveniently -- those we'll still need to add by hand if we want them.

cc @NoRedInk/design thoughts?

**Comment by bendansby** [comment]
Makes sense to me 👍

**Comment by nyghtly-derek** [comment]
I encountered [an example](https://github.com/NoRedInk/NoRedInk/pull/42044) of this today where the new tab link is _within_ a tooltip. I'm not sure if that matters, but wanted to flag just in case there could a problem with tooltip inception.

**Comment by tesk9** [comment]
This is un-done in https://github.com/NoRedInk/noredink-ui/pull/1246 for [reasons explained in slack](https://noredink.slack.com/archives/C9MEFL3KL/p1674515210335959) for ClickableSvgs. We'll need to figure something out for ClickableSvgs still!
