### ISSUE TITLE
Inline ClickableText should inherit font family, weight, and size of parent paragraph

### ISSUE THREAD

**Issue by bendansby** [NoRedInk/noredink-ui#1364]
Currently these must be set manually, leading to mismatches as in the CC example:

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/13528834/233204703-83d0eb2d-86b1-4d14-be07-9e6be571a09a.png">

**Comment by krinhorn** [comment]
[Issue in Linear](https://linear.app/noredink/issue/A11-3900/clickabletext-dont-break-to-next-line-inherit-parent-text-properties)
