### ISSUE TITLE
Heading.markdown puts a paragraph inside the header

### ISSUE THREAD

**Issue by ap-nri** [NoRedInk/noredink-ui#1423]
Paragraphs `p` are not valid inside of header elements `h1`–`h6` so we should leave off the wrapping paragraph around generated markdown. I took a peek* and mine is the only usage of `Heading.markdown` so that's why you're catching it now.

To reproduce: 

```elm
import Nri.Ui.Heading.V3 as Heading

prompt = { assignmentName = "*Esperanza Rising* Discussion Questions" }

Heading.h3
    [ Heading.markdown prompt.assignmentName ]
```

expected generated DOM

```html
<h3><em>Esperanza Rising</em> Discussion Questions</h3>
```

actual generated DOM

```html
<h3><p><em>Esperanza Rising</em> Discussion Questions</p></h3>
```

workaround to at least get rid of the default paragraph margins. 

```elm
Heading.h3
    [ Heading.markdown prompt.assignmentName
    , Heading.css
        [ Css.Global.children
            [ Css.Global.typeSelector "p"
                [ Css.margin Css.zero
                ]
            ]
        ]
```

While we're here we may point out that `*Book Title*` is very lossy in Markdown. The produced text is in italics, yes, but it's definitely not `<em>`. It should probably be a `<cite>` [according to the WHATWG](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-cite-element) but many other sources say it should only be used near a `<q>` or `<blockquote>`. But that's kind of silly because there's no `for` attribute to tie it to the quotation. And also there's no `<author>` element to flesh out the citation. 

---
\* Every `import Nri.Ui.Heading.V` ends with `as Heading` in `monolith` and `lib` and there is no usage of `Heading.markdown` in those same locations.

**Comment by asterite** [comment]
I started working on this out of curiosity, digging into the Markdown library... and eventually realizing the solution is probably calling `markdownInline` instead of `markdownContent`:

https://github.com/NoRedInk/noredink-ui/blob/59dc06439546fd222762e26ac924b9447d197ad0/src/Content.elm#L56-L59

here:

https://github.com/NoRedInk/noredink-ui/blob/59dc06439546fd222762e26ac924b9447d197ad0/src/Nri/Ui/Heading/V3.elm#L117
