### ISSUE TITLE
Improve inline ClickableText

### ISSUE THREAD

**Issue by bendansby** [NoRedInk/noredink-ui#1431]
If I use `ClickableText.appearsInline`, the link receives an underline, but does not actually appear totally inline:

<img width="659" alt="image" src="https://github.com/NoRedInk/noredink-ui/assets/13528834/74410d1e-5683-4c32-9c4b-0c4ec4dc5d36">

(it does if there is enough room for the whole thing)

<img width="560" alt="image" src="https://github.com/NoRedInk/noredink-ui/assets/13528834/c01a9de3-93fe-400d-994d-1a9d2b35932c">

To make it appear truly inline, I need to add `ClickableText.css [ Css.display Css.inline ]`:

<img width="653" alt="image" src="https://github.com/NoRedInk/noredink-ui/assets/13528834/cb1f3e17-12ba-4c50-bb3d-7eed81ed741f">

But then if I use `ClickableText.linkExternal`, it no longer appears inline:

<img width="641" alt="image" src="https://github.com/NoRedInk/noredink-ui/assets/13528834/ff57442d-2159-4e88-aa61-b0bb38a6ec4d">

**Comment by krinhorn** [comment]
[Issue in Linear](https://linear.app/noredink/issue/A11-3900/clickabletext-dont-break-to-next-line-inherit-parent-text-properties)
