### ISSUE TITLE
Improve CC command-click behavior

### ISSUE THREAD

**Issue by bendansby** [NoRedInk/noredink-ui#1474]
- Don't load component page in current tab as well as new tab
- Make command-click work with entire preview container

**Comment by tesk9** [comment]
Command+click isn't working?

**Comment by bendansby** [comment]
Tisn't!

**Comment by bendansby** [comment]
Ohh it does but only if I click the actual component name. OK, good nuff

**Comment by bendansby** [comment]
Ohhh but even then it loads the clicked page in the same tab _as well_. Re-opening and re-wording!

**Comment by tesk9** [comment]
I just had that same _first_ realization!

This makes me wonder about our guidance for clickable cards in general. If we're making the actual anchor part of the link much smaller, that will make the cmd-click-able area of the card smaller & less convenient. 🤔 

Maybe when we have clickable cards containing anchors, we should also be checking for modifier keys being pressed at the same time.

For the _second_ realization -- good catch!
