### ISSUE TITLE
Show default cursor when hovering on a hover-activated tooltip

### ISSUE THREAD

**Issue by bendansby** [NoRedInk/noredink-ui#1558]
Rather than the pointer cursor, which suggests clickability

**Comment by krinhorn** [comment]
@bendansby I can't replicate using the tooltip examples at [the bottom of this page](https://noredink-ui.netlify.app/#/doodad/Tooltip), at least in Chrome. Can you share a specific example or two?

**Comment by bendansby** [comment]
Ah maybe the problem is implementation then:


https://github.com/NoRedInk/noredink-ui/assets/13528834/83f14128-efaf-4e55-91eb-e6f9bd7335f3


https://github.com/NoRedInk/noredink-ui/assets/13528834/b35cbf09-1c1f-4016-918e-013f6bd7b997

**Comment by krinhorn** [comment]
Ohh,I misunderstood the issue!

However, I think this is expected, because clicking still opens/closes the tooltip.

**Comment by bendansby** [comment]
This would just be for hover-activated tooltips, which don't close on click (at least in the examples I recorded above) and whose cursor would be irrelevant in a touch context but relevant in a mouse context.

**Comment by krinhorn** [comment]
Okay, so...
- These close & open on click in the component catalog
- In your first video, the (?) icon closes & opens on click but the integration icon one doesn't (but should)
- I don't know how to get into the state in the second video so can't test

Based on that, I think maybe a bug should be filed with the integrations team to make the tooltip close & open on click. It's possible there's some bug on the noredink-ui side, but I don't see one in the component catalog so I think a dev on integrations would need to check first.
