### ISSUE TITLE
Dropdown isn't stylable without hacky styles

### ISSUE THREAD

**Issue by glitteringkatie** [NoRedInk/noredink-ui#231]
Would be nice if Dropdown took a styles argument

current use case: making the select fill 100% of the container div's width

**Comment by tesk9** [comment]
I wonder if https://noredink-ui.netlify.com/#doodad/Nri.Ui.Select.V3 would meet your needs?

**Comment by glitteringkatie** [comment]
Our input is for gender so we opted for `dropdown` to avoid having a default choice

**Comment by glitteringkatie** [comment]
Now that I've updated Select to allow for default choices, Select V6 meets my needs!
