### ISSUE TITLE
Add Text.mediumBodyGray

### ISSUE THREAD

**Issue by tesk9** [NoRedInk/noredink-ui#547]
Same as mediumBody but with gray45

**Comment by BrianHicks** [comment]
@tesk9 this doesn't feel super necessary to me. It looks like there are two instances where we need this and they can both be called as

```elm
mediumBody
    [ css [ color Colors.gray45 ] ]
    [ text "whatever" ]
```

Are there a bunch more I didn't find, or maybe some where there's a global style set that you know about?

**Comment by tesk9** [comment]
I think that @staceyadams and I were pairing on something and needed a mediumBodyGray. To my mind, this is less about ease of use as a developer and more about presenting a clear and comprehensive styleguide of design components. 🤷‍♀️ 
It's definitely an enhancement rather than a must have, though

**Comment by staceyadams** [comment]
I think this was for the GD rubric intro modal. And we'll be changing that text back to the non-gray during partial essay 😅

**Comment by BrianHicks** [comment]
"comprehensive styleguide" makes sense to me… I'll just add it and we'll have it next time we need it.
