### ISSUE TITLE
modals should not expand proportional to their surroundings

### ISSUE THREAD

**Issue by BrianHicks** [NoRedInk/noredink-ui#598]
modals currently expand vertically on super tall viewports. They shouldn't do that!

![image (3)](https://user-images.githubusercontent.com/355401/92607730-2215b000-f27a-11ea-899b-c37560727a02.png)

**Comment by staceyadams** [comment]
The expanding is even more obvious/egregious on modals that only have a single line of text in the body:
![image](https://user-images.githubusercontent.com/10527520/92623247-d44d7780-f27a-11ea-8c0e-573036c921ed.png)


The modals are still usable though and it's unlikely that users have viewports this tall so historically, this hasn't been prioritized.
