### ISSUE TITLE
Travis does not execute an `elm-package diff`

### ISSUE THREAD

**Issue by jwoudenberg** [NoRedInk/noredink-ui#60]
Running `elm-package diff` and checking that it doesn't return a nonzero exit code ensures the library compiles, has all the required doc comments, and should be ready for publishing. This check does not seem to be running on Travis at the moment.

We should make sure that running `make ci` also runs this check.

**Comment by jwoudenberg** [comment]
@BrianHicks do you have an idea about how to approach this? I guess we should make a change on this line to ensure a nonzero exit of `elm-package diff` propagates upwards, but I'm not sure how:

https://github.com/NoRedInk/noredink-ui/blob/5c203314c62236650fe52e61eebf367ade97cb4d/Makefile#L11

**Comment by BrianHicks** [comment]
How odd! It should be doing the right thing as-is. I tested it with that, and it looks like it hasn’t changed. Did the output change to JSON or something in the environment?

**Comment by jwoudenberg** [comment]
Tested this locally and could reproduce the following:
- If I have a missing doc-comment or something and run `elm-package diff`, I get a nonzero exit code and an error.
- If I run `make ci` I see the same error printed to the command line (among other things), but the exit code at the end is 0.
