### ISSUE TITLE
Checkbox classnames should be versioned to prevent global style collisions

### ISSUE THREAD

**Issue by tesk9** [NoRedInk/noredink-ui#83]
<img width="1302" alt="screen shot 2018-06-27 at 10 44 07 am" src="https://user-images.githubusercontent.com/8811312/41990397-236c4da4-79f7-11e8-89cf-c9a640e0c7d5.png">
<img width="355" alt="screen shot 2018-06-27 at 10 43 29 am" src="https://user-images.githubusercontent.com/8811312/41990398-23868282-79f7-11e8-98e7-7a67e141f6ac.png">

The monolith styles make the checkbox look pretty terrible as-is, as it turns out!

I expect we should follow some kind of class name scheme. Probably `checkbox-v3__Checked` or something like that.

**Comment by BrianHicks** [comment]
**interior, day, a classroom somewhere in America.**

teacher: Bobby, is your writing convincing?

student: well…

David Caruso (crashing through window): did you… CHECK?

**smash cut to CSI: Miami opening credits**
