### ISSUE TITLE
Add more convenient API for hiding icons on mobile

### ISSUE THREAD

**Issue by tesk9** [NoRedInk/noredink-ui#831]

**Comment by tesk9** [comment]
@bendansby Brian C and I extended Button, ClickableText, and Message in order to make the icons easier to hide on mobile. Are there other components that we should do this work for, do you think?

**Comment by bendansby** [comment]
Nothing coming to mind, think those are the big 3!

**Comment by tesk9** [comment]
Woo, calling this done then!
