### ISSUE TITLE
Add Shadow.V1 

### ISSUE THREAD

**Issue by tesk9** [NoRedInk/noredink-ui#843]
See https://github.com/NoRedInk/noredink-ui/pull/842

How many different types of box shadow should a project have? Different "intensities", maybe?

**Comment by bendansby** [comment]
My answer to your question: https://paper.dropbox.com/doc/UI-Style-Guide-and-Caveats--Bchrvv5_p4rudpwMRawcKJTEAg-PvOLxeX3oyujYEzdJx5pu#:uid=984733103055528053538389&h2=Shadows

Cribbed from https://www.joshwcomeau.com/css/introducing-shadow-palette-generator/
