### ISSUE TITLE
Is it possible to use PremiumCheckbox?

### ISSUE THREAD

**Issue by SamGerber** [NoRedInk/noredink-ui#85]
It seems like Nri.Ui.PremiumCheckbox.V1.PremiumConfig requires providing Nri.Ui.Data.PremiumLevel s?

https://github.com/NoRedInk/noredink-ui/blob/0a028997d13ce4652124845b25a5b794e4ec53ce/src/Nri/Ui/PremiumCheckbox/V1.elm#L30-L31

But the elm-package doesn't appear to expose PremiumLevel.
https://github.com/NoRedInk/noredink-ui/blob/0a028997d13ce4652124845b25a5b794e4ec53ce/elm-package.json#L9-L53

Is this a possible explanation for why I'm struggling to use PremiumCheckbox, or am I just doing things incorrectly? I appreciate any help on how to use this! Thanks <3

**Comment by tesk9** [comment]
Oops! Sorry about that, Sam. Exposing should make it possible to use the premium checkbox, but might be kinda complicated on the monolith side depending on how many references to the Nri.Data.PremiumLevel there are/how intertwined they are.

I wonder if there's a way to decouple the Nri.Ui.Data.PremiumLevel from the Premium checkbox -- it seems kind of strange for a view component to depend on a specific NRI data type...? Maybe not.

**Comment by tesk9** [comment]
Did anything end up changing here? Are premium checkboxes usable, or constrained to the monolith?

**Comment by SamGerber** [comment]
I used the deprecated ones in the monolith for what I was working on.

**Comment by jamesgary** [comment]
Just to follow up: https://github.com/NoRedInk/noredink-ui/pull/111 has been merged and published, so you ought to be able to use `Nri.Ui.PremiumCheckbox.V2` without `PremiumLevel`s.
