### ISSUE TITLE
input fields should all have white backgrounds

### ISSUE THREAD

**Issue by BrianHicks** [NoRedInk/noredink-ui#87]
basically what this says in the title. 😄 Inputs should look the same regardless of what background color we put them on (with grey or white being the only current concerns.)

@bendansby do you want to share that screenshot here to illustrate? Up to you.

**Comment by bendansby** [comment]
<img width="412" alt="image" src="https://user-images.githubusercontent.com/13528834/42830912-b1e35b2c-89a1-11e8-9e25-b970dadff653.png">

**Comment by BrianHicks** [comment]
Looks like this may be true already!

![image](https://user-images.githubusercontent.com/355401/43331455-906624ce-918b-11e8-9e1c-ecab2de78a3d.png)

Do we know of any specific input types (other than the old datepickers outside this repo) that have this problem?

**Comment by BrianHicks** [comment]
(@staceyadams @tesk9 may have more context on this)

**Comment by BrianHicks** [comment]
closing based on internal discussions with Stacey. 😄 Looks like this was a concern but is fixed in the repo going forward.
