### ISSUE TITLE
Add azure border to checked state of checkboxes

### ISSUE THREAD

**Issue by bendansby** [NoRedInk/noredink-ui#965]
This is currently implemented only on the Assignment Library; it should be global. Make sure the global update doesn't conflict with this local AL implementation.

<img width="662" alt="image" src="https://user-images.githubusercontent.com/13528834/175983982-a3bd17c7-b91c-4af0-9488-54d655a9ccc7.png">

**Comment by tesk9** [comment]
I think we may want to change the AL implementation strategy, though? The border doesn't hug the contents the way I want it to:

<img width="116" alt="" src="https://user-images.githubusercontent.com/8811312/176062097-de89cd90-2a9d-4cbc-8ec6-fab3de7dd948.png">

**Comment by bendansby** [comment]
Agreed, we want firm hugs!
